name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:  # Allows manual execution

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Pull the latest code

      - name: Get Short Commit SHA
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker Image
        run: |
         docker build -t bhupendrargoud/sensy:latest .
         docker tag bhupendrargoud/sensy:latest bhupendrargoud/sensy:${{ env.SHORT_SHA }}

      - name: Push Docker Image
        run: docker push bhupendrargoud/sensy:${{ env.SHORT_SHA }}
  update-deployment:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Pull the latest code

      - name: Get Short Commit SHA
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name :  git config
        run : |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Checkout Deployment Repo
        run: |
          git clone -b master git@github.com:bhupendrargoud/infra.git
          ls -la
          

      - name: Set Python Environment
        run: python -m pip install --upgrade pip pyyaml

      - name: Update Image Tag in Deployment YAML
        run: |
          cd infra/manifests/code
          ls -la
          python update_image.py -v bhupendrargoud/sensy:${{ env.SHORT_SHA }} 

          git add deployment.yaml
          git commit -m "image tag : ${{ env.SHORT_SHA }}"
          git push origin master
